apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: spring-sensors
  description: Spring Sensors Application
spec:
  owner: dev-team-2
  domain: acme-internal-apps

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-sensors
  description: Spring Sensors Spring Boot
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-sensors'
spec:
  type: service
  lifecycle: alpha
  owner: dev-team-2
  system: spring-sensors

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rabbitmq
  description: Tanzu RabbitMQ Service
spec:
  type: messaging
  owner: platform-team
  system: spring-sensors
---
